name: Report an issue with the Climate Schedule Card
description: Report an issue with the HomematicIP Local Climate Schedule Card
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!
        Use [Discussions](https://github.com/SukramJ/homematicip_local_climate_schedule_card/discussions) for feature requests, questions, and other topics.

        **Note:** Active development happens in the [homematicip-local-frontend](https://github.com/SukramJ/homematicip-local-frontend) monorepo. Depending on the issue, you may be redirected there.

        Please avoid unnecessary effort by reading the points below.
  - type: checkboxes
    attributes:
      label: I agree to the following
      options:
        - label: I have read the [README / documentation](https://github.com/SukramJ/homematicip_local_climate_schedule_card#readme) including the troubleshooting section
          required: true
        - label: I have cleared my browser cache (Ctrl+F5 / Cmd+Shift+R) and the issue persists
          required: true
        - label: I am running the latest version of the card. See [releases](https://github.com/SukramJ/homematicip_local_climate_schedule_card/releases). I am also running the latest version of Home Assistant.
          required: true
        - label: I am running the latest version of the HomematicIP Local integration. See [releases](https://github.com/sukramj/homematicip_local/releases).
          required: true
        - label: I have checked the [existing issues](https://github.com/SukramJ/homematicip_local_climate_schedule_card/issues) to make sure this hasn't been reported already
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Please answer the following questions:

        1. **What is happening?** (Describe the actual behavior)

        2. **When/How does it occur?** (After page reload, when editing, when switching profiles, with specific devices, ...)

        3. **What did you expect?** (Describe the expected behavior)

        4. **What have you tried?** (Browser cache cleared, different browser, card reinstalled, ...)

        NO logs or configuration here!
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: card_version
    validations:
      required: true
    attributes:
      label: Card version
      placeholder: 0.10.0
      description: >
        Can be found in: HACS -> Frontend -> HomematicIP Local Climate Schedule Card
  - type: input
    attributes:
      label: Last working card version
      placeholder: 0.9.0
      description: >
        If known, otherwise leave blank.
  - type: input
    id: ha_version
    validations:
      required: true
    attributes:
      label: Home Assistant version
      placeholder: "2025.12.0"
      description: >
        Can be found in: [Settings -> System -> Repairs -> Three Dots -> System information](https://my.home-assistant.io/redirect/system_health/)
  - type: input
    id: integration_version
    validations:
      required: true
    attributes:
      label: HomematicIP Local integration version
      placeholder: 2.x.x
      description: >
        Can be found in: HACS -> Integrations -> HomematicIP Local
  - type: dropdown
    validations:
      required: true
    attributes:
      label: How was the card installed?
      options:
        - HACS
        - Manual installation
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Browser / Client
      description: >
        Which browser or client are you using?
      options:
        - Google Chrome
        - Mozilla Firefox
        - Safari
        - Microsoft Edge
        - Home Assistant Companion App (Android)
        - Home Assistant Companion App (iOS)
        - Other (please specify below)
  - type: markdown
    attributes:
      value: |
        ## Card Details
  - type: textarea
    validations:
      required: true
    attributes:
      label: Card configuration (YAML)
      description: >-
        Paste your card configuration here.

        **How to get it**: Open the card editor -> Show code editor -> Copy the YAML
      render: yaml
      placeholder: |
        type: custom:homematicip-local-climate-schedule-card
        entity: climate.your_thermostat
  - type: textarea
    attributes:
      label: Screenshots
      description: >-
        Screenshots are extremely helpful, especially for visual issues!

        Please include:

        - A screenshot of the card showing the issue

        - If possible, also a screenshot of the expected behavior (e.g., from the CCU or a previous version)
  - type: textarea
    attributes:
      label: Browser console errors
      description: >-
        Open the browser developer tools (F12) -> Console tab -> Reproduce the issue.

        Copy any error messages that appear (especially those mentioning the card name).
      render: text
      placeholder: "Paste browser console errors here"
  - type: textarea
    attributes:
      label: Additional information
      description: >
        Any additional context, e.g. which thermostat model you're using (HmIP-eTRV, HmIP-BWTH, ...),
        number of profiles, or steps to reproduce the issue.
