name: Melde ein Problem mit der Climate Schedule Card
description: Melde ein Problem mit der HomematicIP Local Climate Schedule Card
body:
  - type: markdown
    attributes:
      value: |
        Dieses Formular dient ausschließlich zur Meldung von Fehlern!
        Nutze die [Diskussionen](https://github.com/SukramJ/homematicip_local_climate_schedule_card/discussions) für Funktionswünsche, Fragen und andere Themen.

        **Hinweis:** Die aktive Entwicklung findet im [homematicip-local-frontend](https://github.com/SukramJ/homematicip-local-frontend) Monorepo statt. Je nach Problem kann es sein, dass Du dorthin weitergeleitet wirst.

        Bitte vermeide unnötigen Aufwand, indem die folgenden Punkte aufmerksam gelesen werden.
  - type: checkboxes
    attributes:
      label: Ich stimme dem Folgenden zu
      options:
        - label: Ich habe die [README / Dokumentation](https://github.com/SukramJ/homematicip_local_climate_schedule_card#readme) inklusive des Abschnitts zur Fehlerbehebung gelesen
          required: true
        - label: Ich habe den Browser-Cache geleert (Strg+F5 / Cmd+Shift+R) und das Problem besteht weiterhin
          required: true
        - label: Ich verwende die neueste Version der Card. Siehe [Releases](https://github.com/SukramJ/homematicip_local_climate_schedule_card/releases). Ich verwende auch die neueste Version von Home Assistant.
          required: true
        - label: Ich verwende die neueste Version der HomematicIP Local Integration. Siehe [Releases](https://github.com/sukramj/homematicip_local/releases).
          required: true
        - label: Ich habe die [bestehenden Issues](https://github.com/SukramJ/homematicip_local_climate_schedule_card/issues) geprüft und sichergestellt, dass dieses Problem noch nicht gemeldet wurde
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: Das Problem
      description: >-
        Bitte beantworte die folgenden Fragen:

        1. **Was passiert?** (Beschreibe das tatsächliche Verhalten)

        2. **Wann/Wie tritt es auf?** (Nach Seiten-Reload, beim Bearbeiten, beim Profil-Wechsel, bei bestimmten Geräten, ...)

        3. **Was hast Du erwartet?** (Beschreibe das erwartete Verhalten)

        4. **Was hast Du bereits versucht?** (Browser-Cache geleert, anderer Browser, Card neu installiert, ...)

        Keine Logs oder Konfigurationen hier!
  - type: markdown
    attributes:
      value: |
        ## Systemumgebung
  - type: input
    id: card_version
    validations:
      required: true
    attributes:
      label: Card-Version
      placeholder: 0.10.0
      description: >
        Zu finden unter: HACS -> Frontend -> HomematicIP Local Climate Schedule Card
  - type: input
    attributes:
      label: Letzte funktionierende Card-Version
      placeholder: 0.9.0
      description: >
        Falls bekannt, andernfalls leer lassen.
  - type: input
    id: ha_version
    validations:
      required: true
    attributes:
      label: Home Assistant Version
      placeholder: "2025.12.0"
      description: >
        Zu finden unter: [Einstellungen -> System -> Reparaturen -> Drei Punkte -> Systeminformation](https://my.home-assistant.io/redirect/system_health/)
  - type: input
    id: integration_version
    validations:
      required: true
    attributes:
      label: HomematicIP Local Integrations-Version
      placeholder: 2.x.x
      description: >
        Zu finden unter: HACS -> Integrationen -> HomematicIP Local
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Wie wurde die Card installiert?
      options:
        - HACS
        - Manuelle Installation
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Browser / Client
      description: >
        Welchen Browser oder Client verwendest Du?
      options:
        - Google Chrome
        - Mozilla Firefox
        - Safari
        - Microsoft Edge
        - Home Assistant Companion App (Android)
        - Home Assistant Companion App (iOS)
        - Anderer (bitte unten angeben)
  - type: markdown
    attributes:
      value: |
        ## Card-Details
  - type: textarea
    validations:
      required: true
    attributes:
      label: Card-Konfiguration (YAML)
      description: >-
        Füge hier Deine Card-Konfiguration ein.

        **So findest Du sie**: Card-Editor öffnen -> Code-Editor anzeigen -> YAML kopieren
      render: yaml
      placeholder: |
        type: custom:homematicip-local-climate-schedule-card
        entity: climate.dein_thermostat
  - type: textarea
    attributes:
      label: Screenshots
      description: >-
        Screenshots sind extrem hilfreich, besonders bei visuellen Problemen!

        Bitte füge hinzu:

        - Einen Screenshot der Card, der das Problem zeigt

        - Wenn möglich, auch einen Screenshot des erwarteten Verhaltens (z.B. von der CCU oder einer früheren Version)
  - type: textarea
    attributes:
      label: Browser-Konsolenfehler
      description: >-
        Öffne die Browser-Entwicklertools (F12) -> Tab "Konsole" -> Problem reproduzieren.

        Kopiere alle Fehlermeldungen, die erscheinen (insbesondere solche, die den Card-Namen erwähnen).
      render: text
      placeholder: "Browser-Konsolenfehler hier einfügen"
  - type: textarea
    attributes:
      label: Weitere Informationen
      description: >
        Zusätzlicher Kontext, z.B. welches Thermostat-Modell Du verwendest (HmIP-eTRV, HmIP-BWTH, ...),
        Anzahl der Profile, oder Schritte zur Reproduktion des Problems.
